---
- name: Terminate environment
  hosts: localhost
  gather_facts: no
  connection: local

  vars_files:
    - ../../vars/secrets.yml
    - ../../vars/gcp.yml
  vars:
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:
    - name: Terminate instances
      include: gcp_terminate_instance.yml item={{ instance }}
      delegate_to: 127.0.0.1
      with_items:
        - eu-gcp-web-linux-1
        - eu-gcp-web-linux-2
        - eu-gcp-web-windows-1
        - eu-gcp-web-windows-2
      loop_control:
        loop_var: instance

    - name: Terminate the firewall
      gcp_compute_firewall:
        name: ansible-firewall
        project: "{{ project_id }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        scopes: "{{ scopes }}"
        state: absent

    - name: Terminate the network
      gcp_compute_network:
        name: network-instance
        project: "{{ project_id }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        scopes: "{{ scopes }}"
        state: absent
