---
- name: Reset windows administrator password
  hosts: tag_windows
  gather_facts: no
  debugger: on_failed
  connection: local

  vars_files:
    - ../../vars/secrets.yml
    - ../../vars/gcp.yml
  vars:
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:
    - name: Password
      debug:
        msg: "{{ inventory_hostname.name }}"

    - name: Create admin password
      delegate_to: 127.0.0.1
      command: gcloud beta compute --project "{{ project_id }}" reset-windows-password "{{ inventory_hostname }}" --zone "{{ zone }}" --quiet
      retries: 6
      delay: 5
      register: username_password
      until: username_password.rc == 0

    - name: Password
      debug:
        msg: "{{ username_password.stdout_lines[1] }}"
    - name: Username
      debug:
        msg: "{{ username_password.stdout_lines[2] }}"

    - name: Create subdirectory
      delegate_to: 127.0.0.1
      file:
        path: "./group_vars/tag_windows"
        state: directory

    - name: Configure group_vars for windows instance
      delegate_to: 127.0.0.1
      copy:
        dest: "./group_vars/tag_windows/ec-gcp-web-2"
        content: |
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_password: {{ username_password.stdout_lines[1] | regex_replace('password:') }}
          ansible_user: {{ username_password.stdout_lines[2] | regex_replace('username:') }}
