---
- name: Deploy Deep Security Agent on linux and windows
  hosts: tag_windows, tag_linux
  debugger: on_failed

  vars_files:
    - ../../vars/secrets.yml
    - ../../vars/gcp.yml

  tasks:
    - name: Including Role
      include_role:
        name: deep-security.deep-security-agent
      vars:
        operation: deploy
        dsm_agent_download_hostname: "{{ agent_download_hostname }}"
        dsm_agent_download_port: "{{ agent_download_port }}"
        dsm_agent_activation_hostname: "{{ agent_activation_hostname }}"
        dsm_agent_activation_port: "{{ agent_activation_port }}"
        force_reactivation: False

- name: Set Ubuntu 16 Web Server policy
  hosts: tag_linux
  tasks:
    - name: Set Policy
      include_role:
        name: deep-security.deep-security-agent
      vars:
        operation: set-policy-by-name
        policy_name: Linux Web Server

- name: Set Windows 2012R2 Web Server policy
  hosts: tag_windows
  tasks:
    - name: Set Policy
      include_role:
        name: deep-security.deep-security-agent
      vars:
        operation: set-policy-by-name
        policy_name: Windows Web Server

- name: Update Configuration
  hosts: tag_windows, tag_linux
  tasks:
    - name: Update Configuration
      include_role:
        name: deep-security.deep-security-agent
      vars:
        operation: update-configuration
    - name: Initiate Recommendation Scan
      include_role:
        name: deep-security.deep-security-agent
      vars:
        operation: run-recommendation-scans

- name: Prepare Facter for Deep Security
  hosts: tag_linux
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
    - name: Install the latest version of "facter"
      apt:
        name: facter
        state: present
    - name: "Create custom fact directory"
      file:
        path: "/etc/ansible/facts.d"
        state: "directory"
    - name: "Insert custom fact file"
      copy:
        src: ../../files/dsa_status.fact
        dest: /etc/ansible/facts.d/dsa_status.fact
        mode: 0755
